//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPepak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kewan
    {
        public Kewan()
        {
            this.Kuis = new HashSet<Kuis>();
        }
    
        public int KewanId { get; set; }
        public string NamaKewan { get; set; }
        public string AnakKewan { get; set; }
    
        public virtual ICollection<Kuis> Kuis { get; set; }
    }
}
