//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPepak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuis
    {
        public int KuisId { get; set; }
        public string Pertanyaan { get; set; }
        public Nullable<int> KewanId { get; set; }
        public Nullable<int> KembangId { get; set; }
    
        public virtual Kewan Kewan { get; set; }
        public virtual Tetuwuhan Tetuwuhan { get; set; }
    }
}
