//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPepak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tetuwuhan
    {
        public Tetuwuhan()
        {
            this.Kuis = new HashSet<Kuis>();
        }
    
        public int KembangId { get; set; }
        public string Tetuwuhan1 { get; set; }
        public string AraneKembang { get; set; }
    
        public virtual ICollection<Kuis> Kuis { get; set; }
    }
}
